# Generated by Django 4.0.6 on 2023-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=40)),
                ('date_of_birth', models.DateField()),
                ('school', models.CharField(default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=40)),
                ('intro', models.CharField(blank=True, default='', max_length=511)),
                ('skills', models.CharField(blank=True, default='', max_length=511)),
                ('experience', models.CharField(blank=True, default='', max_length=511)),
                ('initiatives', models.CharField(blank=True, default='', max_length=511)),
            ],
        ),
    ]
